# Generated by Django 5.2.14 on 2026-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='explainabilityreport',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='graphsnapshot',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lobrun',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portfoliorun',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='regimerun',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='riskrun',
            name='feature_schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
