# Generated by Django 5.2.14 on 2026-05-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "pdf_file",
                    models.FileField(blank=True, upload_to="quantspace/papers/"),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sha256"], name="quantspace__sha256_e83032_idx"
                    ),
                    models.Index(fields=["title"], name="quantspace__title_9717c6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaperChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("page_start", models.PositiveIntegerField()),
                ("page_end", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("embedding_json", models.JSONField(blank=True, default=list)),
                (
                    "support_status",
                    models.CharField(
                        choices=[
                            ("SUPPORTED", "Supported"),
                            ("PARTIAL", "Partial"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="SUPPORTED",
                        max_length=32,
                    ),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="quantspace.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["paper_id", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="PaperQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("prompt_preview", models.TextField(blank=True)),
                ("llm_provider", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(default="RETRIEVAL_ONLY", max_length=32)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quantspace.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_start", models.PositiveIntegerField()),
                ("page_end", models.PositiveIntegerField()),
                ("quote", models.TextField(blank=True)),
                (
                    "support_status",
                    models.CharField(
                        choices=[
                            ("SUPPORTED", "Supported"),
                            ("PARTIAL", "Partial"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="SUPPORTED",
                        max_length=32,
                    ),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quantspace.paperchunk",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="quantspace.paper",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="quantspace.paperquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["paper_id", "page_start"],
            },
        ),
        migrations.CreateModel(
            name="QuantExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extraction_json", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.TextField(blank=True)),
                ("prompt_preview", models.TextField(blank=True)),
                (
                    "support_status",
                    models.CharField(
                        choices=[
                            ("SUPPORTED", "Supported"),
                            ("PARTIAL", "Partial"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=32,
                    ),
                ),
                ("status", models.CharField(default="DRAFT", max_length=32)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="quantspace.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FactorCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("expression_json", models.JSONField(blank=True, default=dict)),
                ("rationale", models.TextField(blank=True)),
                ("prompt_preview", models.TextField(blank=True)),
                (
                    "support_status",
                    models.CharField(
                        choices=[
                            ("SUPPORTED", "Supported"),
                            ("PARTIAL", "Partial"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=32,
                    ),
                ),
                ("status", models.CharField(default="NEEDS_BACKTEST", max_length=40)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factors",
                        to="quantspace.paper",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factors",
                        to="quantspace.quantextraction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artifact_type", models.CharField(max_length=80)),
                ("path", models.CharField(blank=True, max_length=1200)),
                ("content", models.TextField(blank=True)),
                (
                    "support_status",
                    models.CharField(
                        choices=[
                            ("SUPPORTED", "Supported"),
                            ("PARTIAL", "Partial"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=32,
                    ),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="quantspace.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["paper", "artifact_type"],
                        name="quantspace__paper_i_4293aa_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paperchunk",
            index=models.Index(
                fields=["paper", "page_start", "page_end"],
                name="quantspace__paper_i_acee5a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paperchunk",
            constraint=models.UniqueConstraint(
                fields=("paper", "chunk_index"), name="uniq_quantspace_paper_chunk"
            ),
        ),
        migrations.AddIndex(
            model_name="factorcandidate",
            index=models.Index(
                fields=["status", "support_status"],
                name="quantspace__status_328069_idx",
            ),
        ),
    ]
