# Generated by Django 5.2.14 on 2026-05-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant4', '0002_backtestrun_feature_schema_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphsnapshot',
            name='adjacency_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='graphsnapshot',
            name='edge_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='graphsnapshot',
            name='node_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
