# Generated by Django 5.2.14 on 2026-05-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant4', '0003_graphsnapshot_adjacency_path_graphsnapshot_edge_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliorun',
            name='risk_report_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portfoliorun',
            name='trades_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='portfoliorun',
            name='weights_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
