"""Named defaults for local Quant multifractal workflows."""

from __future__ import annotations

DEFAULT_DIAGNOSTIC_SEED = 17
DEFAULT_MODEL_RANDOM_SEED = 17
DIAGNOSTIC_BOOTSTRAP_COUNT = 4
DIAGNOSTIC_FINITE_SIZE_SIMULATIONS = 2

REPORT_RISK_DELTA_ALPHA = 0.2
REPORT_RISK_INTERMITTENCY = 0.2

DEFAULT_CLI_SERIES = (0.01, -0.02, 0.015, -0.005) * 16

REGIME_STRESS_DRAWDOWN_THRESHOLD = -0.15
REGIME_STRESS_LIQUIDITY_THRESHOLD = 0.85
REGIME_TREND_HURST_THRESHOLD = 0.58
REGIME_MEAN_REVERSION_HURST_THRESHOLD = 0.42
REGIME_DELTA_ALPHA_FLOOR = 0.45
REGIME_VOLATILITY_FLOOR = 0.025
REGIME_PRIMARY_PROBABILITY = 0.75
REGIME_MIN_PROBABILITY = 0.05
