"""Portable cloud job spec builders."""

from dataclasses import asdict, dataclass
from pathlib import Path
from collections.abc import Mapping

from monitoring.cloud.manifest import utc_timestamp, write_manifest
from monitoring.compute.profiles import ComputeProfile, get_compute_profile
from monitoring.compute.task_registry import get_analytics_task


@dataclass(frozen=True, slots=True)
class CloudJobSpec:
    """Provider-neutral cloud job description.

    Example:
        `spec = create_cloud_job_spec("mfdfa_gpu_batched", "cloud_student", "monthly")`
    """

    schema_version: str
    job_name: str
    task: str
    profile: str
    backend: str
    partition: Mapping[str, object]
    resources: Mapping[str, object]
    budget: Mapping[str, object]
    inputs: Mapping[str, object]
    outputs: Mapping[str, object]
    command: str
    created_at: str
    notes: tuple[str, ...]


def create_cloud_job_spec(
    task: str,
    profile: str = "cloud_student",
    partition: str = "monthly",
    partition_label: str = "2024_01",
) -> CloudJobSpec:
    """Create a provider-neutral job spec for one task partition.

    Example:
        `create_cloud_job_spec("graph_embedding", "cloud_student", "quarterly")`
    """
    get_analytics_task(task)
    compute_profile = get_compute_profile(profile)
    job_name = f"{task}_{partition_label}"
    return CloudJobSpec(
        "1.0",
        job_name,
        task,
        compute_profile.name,
        "gpu",
        _partition_payload(partition, partition_label),
        _resource_payload(compute_profile),
        _budget_payload(compute_profile),
        _input_payload(task),
        _output_payload(task, partition_label),
        _job_command(task, compute_profile.name, partition_label),
        utc_timestamp(),
        ("Generated by portable planner; no provider SDK required.",),
    )


def write_cloud_job_spec(spec: CloudJobSpec, output_dir: Path) -> Path:
    """Write a cloud job spec to an output directory.

    Example:
        `write_cloud_job_spec(spec, Path("exports/cloud_jobs"))`
    """
    output_path = output_dir / f"{spec.job_name}.json"
    return write_manifest(asdict(spec), output_path)


def validate_budget_guard(spec: Mapping[str, object]) -> None:
    """Validate cloud job budget guard fields.

    Example:
        `validate_budget_guard(job_spec)`
    """
    budget = spec.get("budget", {})
    if not isinstance(budget, Mapping):
        raise ValueError(f"Invalid budget {budget!r}; expected JSON object")
    if budget.get("require_confirmation") is not True:
        message = f"Invalid budget {budget!r}; expected require_confirmation=true"
        raise ValueError(message)
    if "max_cost_usd" not in budget:
        raise ValueError(f"Invalid budget {budget!r}; expected max_cost_usd")


def _partition_payload(partition: str, label: str) -> dict[str, object]:
    if partition not in ("daily", "monthly", "quarterly", "yearly"):
        message = (
            f"Invalid partition {partition!r}; "
            "expected daily/monthly/quarterly/yearly"
        )
        raise ValueError(message)
    return {"type": partition, "label": label}


def _resource_payload(profile: ComputeProfile) -> dict[str, object]:
    return {
        "gpu": "optional_or_any",
        "min_vram_gb": profile.max_vram_gb,
        "cpu": 4,
        "ram_gb": profile.max_ram_gb or 16,
        "max_runtime_hours": profile.max_runtime_hours,
    }


def _budget_payload(profile: ComputeProfile) -> dict[str, object]:
    return {
        "max_cost_usd": 0,
        "student_credits": profile.name == "cloud_student",
        "require_confirmation": profile.budget_guard_enabled,
    }


def _input_payload(task: str) -> dict[str, object]:
    return {"feature_store": "exports/local_simple/feature_store.parquet", "task": task}


def _output_payload(task: str, partition_label: str) -> dict[str, object]:
    path = f"exports/cloud/{task}_{partition_label}.parquet"
    return {"artifact": path}


def _job_command(task: str, profile: str, partition_label: str) -> str:
    return (
        "python manage.py run_analytics_pipeline "
        f"--profile {profile} --task {task} --partition {partition_label}"
    )
