# Generated by Django 5.2.14 on 2026-05-09 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240, unique=True)),
                ("normalized_name", models.CharField(max_length=240, unique=True)),
                ("entity_type", models.CharField(default="unknown", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest_date", models.DateField(unique=True)),
                ("title", models.CharField(max_length=240)),
                ("body", models.TextField()),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-digest_date"],
            },
        ),
        migrations.CreateModel(
            name="DigestCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=120, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["cache_key"],
            },
        ),
        migrations.CreateModel(
            name="DocumentEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mention_text", models.CharField(max_length=240)),
                ("mention_count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["document_id", "entity__name"],
            },
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=240)),
                ("alias_normalized", models.CharField(max_length=240, unique=True)),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="EntityRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(default="co_occurs", max_length=80),
                ),
                ("weight", models.PositiveIntegerField(default=1)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-weight", "source_entity__name"],
            },
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="cooldown_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="last_error_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="last_http_status",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="category",
            field=models.CharField(
                choices=[
                    ("world", "World"),
                    ("politics", "Politics"),
                    ("business", "Business"),
                    ("markets", "Markets"),
                    ("technology", "Technology"),
                    ("security", "Security"),
                    ("defense", "Defense"),
                    ("science", "Science"),
                    ("health", "Health"),
                    ("energy", "Energy"),
                    ("climate", "Climate"),
                    ("legal", "Legal"),
                    ("policy", "Policy"),
                    ("culture", "Culture"),
                    ("regional", "Regional"),
                ],
                default="world",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="is_dynamic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="source",
            name="language",
            field=models.CharField(default="en", max_length=16),
        ),
        migrations.AddField(
            model_name="source",
            name="propaganda_risk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="source",
            name="query_template",
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name="source",
            name="reputation_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="source",
            name="source_tier",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="source",
            name="state_affiliation",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["category", "source_tier"],
                name="monitoring__categor_8f0f62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="canonicalentity",
            index=models.Index(
                fields=["entity_type"], name="monitoring__entity__aaefed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digestcache",
            index=models.Index(
                fields=["expires_at"], name="monitoring__expires_e2836d_idx"
            ),
        ),
        migrations.AddField(
            model_name="documententity",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.normalizeddocument",
            ),
        ),
        migrations.AddField(
            model_name="documententity",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.canonicalentity",
            ),
        ),
        migrations.AddField(
            model_name="entityalias",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.canonicalentity",
            ),
        ),
        migrations.AddField(
            model_name="entityrelationship",
            name="source_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_relationships",
                to="monitoring.canonicalentity",
            ),
        ),
        migrations.AddField(
            model_name="entityrelationship",
            name="target_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_relationships",
                to="monitoring.canonicalentity",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.UniqueConstraint(
                fields=("document", "entity"), name="unique_document_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="entityalias",
            index=models.Index(
                fields=["alias_normalized"], name="monitoring__alias_n_f29aa1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationship",
            constraint=models.UniqueConstraint(
                fields=("source_entity", "target_entity", "relationship_type"),
                name="unique_entity_relationship",
            ),
        ),
    ]
