# Generated by Django 5.2.14 on 2026-05-09 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_canonicalentity_dailydigest_digestcache_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword"),
                            ("entity", "Entity"),
                            ("category", "Category"),
                            ("volume", "Volume"),
                        ],
                        max_length=20,
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=240)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("world", "World"),
                            ("politics", "Politics"),
                            ("business", "Business"),
                            ("markets", "Markets"),
                            ("technology", "Technology"),
                            ("security", "Security"),
                            ("defense", "Defense"),
                            ("science", "Science"),
                            ("health", "Health"),
                            ("energy", "Energy"),
                            ("climate", "Climate"),
                            ("legal", "Legal"),
                            ("policy", "Policy"),
                            ("culture", "Culture"),
                            ("regional", "Regional"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("cooldown_minutes", models.PositiveIntegerField(default=60)),
                ("threshold_count", models.PositiveIntegerField(default=1)),
                ("lookback_minutes", models.PositiveIntegerField(default=1440)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_enabled"],
                        name="monitoring__rule_ty_53ecf1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CanonicalUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_url", models.URLField(max_length=1200, unique=True)),
                ("domain", models.CharField(max_length=240)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["domain", "canonical_url"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="monitoring__domain_4c119f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("domain", "Domain"),
                            ("topic", "Topic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("url", models.URLField(max_length=1200)),
                ("evidence_url", models.URLField(blank=True, max_length=1200)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("world", "World"),
                            ("politics", "Politics"),
                            ("business", "Business"),
                            ("markets", "Markets"),
                            ("technology", "Technology"),
                            ("security", "Security"),
                            ("defense", "Defense"),
                            ("science", "Science"),
                            ("health", "Health"),
                            ("energy", "Energy"),
                            ("climate", "Climate"),
                            ("legal", "Legal"),
                            ("policy", "Policy"),
                            ("culture", "Culture"),
                            ("regional", "Regional"),
                        ],
                        max_length=32,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-confidence", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate_type", "url"),
                        name="unique_discovery_candidate",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TopicCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=240)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("entities", models.JSONField(blank=True, default=list)),
                ("document_count", models.PositiveIntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-score", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("label", "window_start"), name="unique_topic_cluster"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dedupe_hash", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("matched_text", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring.normalizeddocument",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring.source",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "status"],
                        name="monitoring__severit_ebe4f2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentEnrichment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_language", models.CharField(blank=True, max_length=16)),
                ("summary", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                (
                    "sentiment_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("quality_flags", models.JSONField(blank=True, default=list)),
                ("enrichment_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.normalizeddocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["detected_language"],
                        name="monitoring__detecte_4bc3b0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentUrlReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(default="canonical", max_length=80),
                ),
                (
                    "canonical_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.canonicalurl",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.normalizeddocument",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "canonical_url", "reference_type"),
                        name="unique_document_url_reference",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceReputationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=4)),
                ("components", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-window_end", "source__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "window_start", "window_end"),
                        name="unique_reputation_snapshot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overlap_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.normalizeddocument",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.topiccluster",
                    ),
                ),
            ],
            options={
                "ordering": ["cluster_id", "-overlap_score"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cluster", "document"), name="unique_document_topic"
                    )
                ],
            },
        ),
    ]
