# Generated by Django 5.2.14 on 2026-05-10 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_exportartifact_nlprunmetric"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertDetector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, unique=True)),
                (
                    "detector_type",
                    models.CharField(
                        choices=[
                            ("emerging_topic", "Emerging topic"),
                            ("anomaly", "Anomaly"),
                            ("entity_burst", "Entity burst"),
                            ("source_burst", "Source burst"),
                            ("market_shock", "Market shock"),
                            ("contradiction", "Contradiction"),
                        ],
                        max_length=40,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "sensitivity",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("useful", "Useful"),
                            ("false_positive", "False positive"),
                            ("duplicate", "Duplicate"),
                            ("too_late", "Too late"),
                            ("too_low_severity", "Too low severity"),
                            ("too_high_severity", "Too high severity"),
                        ],
                        max_length=40,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertHitDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("representative", "Representative"),
                            ("evidence", "Evidence"),
                            ("duplicate", "Duplicate"),
                            ("contradiction", "Contradiction"),
                            ("source_of_claim", "Source of claim"),
                        ],
                        default="evidence",
                        max_length=40,
                    ),
                ),
                (
                    "similarity_to_cluster",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "source_reliability_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("matched_text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["alert_hit_id", "role"],
            },
        ),
        migrations.CreateModel(
            name="DedupeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("near", "Near"),
                            ("semantic", "Semantic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("simhash", models.CharField(blank=True, max_length=64, null=True)),
                ("document_count", models.PositiveIntegerField(default=0)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.AddField(
            model_name="alerthit",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.topiccluster",
            ),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="confidence_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="detected_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="entity_importance_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="market_relevance_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="novelty_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="representative_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="representative_alerts",
                to="monitoring.normalizeddocument",
            ),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="severity_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="source_diversity_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="trend_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("explicit_rule_match", "Explicit rule match"),
                    ("automatic_emerging_cluster", "Automatic cluster"),
                    ("anomaly", "Anomaly"),
                    ("entity_burst", "Entity burst"),
                    ("market_shock", "Market shock"),
                    ("contradiction", "Contradiction"),
                ],
                default="explicit_rule_match",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="entity_filters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="min_novelty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="min_severity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="min_trend",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="source_filters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="topic_filters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="documenttopic",
            name="role",
            field=models.CharField(
                choices=[
                    ("representative", "Representative"),
                    ("evidence", "Evidence"),
                    ("duplicate", "Duplicate"),
                    ("contradiction", "Contradiction"),
                    ("source_of_claim", "Source of claim"),
                ],
                default="evidence",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="documenttopic",
            name="similarity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="normalizeddocument",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="normalizeddocument",
            name="ingested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="normalizeddocument",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="normalizeddocument",
            name="simhash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="normalizeddocument",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="source",
            name="reliability_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="source",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("news", "News"),
                    ("gov", "Government"),
                    ("paper", "Paper"),
                    ("social", "Social"),
                    ("other", "Other"),
                ],
                default="news",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="canonical_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="confidence_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="first_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="novelty_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="severity_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="source_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("stale", "Stale"),
                    ("merged", "Merged"),
                    ("ignored", "Ignored"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="topic_label",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="trend_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
