# Generated by Django 5.2.14 on 2026-05-10 05:47

import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_alert_engine_fields(apps: object, schema_editor: object) -> None:
    Source = apps.get_model("monitoring", "Source")
    Document = apps.get_model("monitoring", "NormalizedDocument")
    Cluster = apps.get_model("monitoring", "TopicCluster")
    AlertHit = apps.get_model("monitoring", "AlertHit")
    AlertHitDocument = apps.get_model("monitoring", "AlertHitDocument")
    _backfill_sources(Source)
    _backfill_documents(Document)
    _backfill_clusters(Cluster)
    _backfill_alerts(AlertHit, AlertHitDocument, Cluster)


def _backfill_sources(Source: object) -> None:
    for source in Source.objects.all():
        source.reliability_score = source.reputation_score
        if source.category == "science":
            source.source_kind = "paper"
        elif source.category in {"policy", "defense"}:
            source.source_kind = "gov"
        source.save(update_fields=["reliability_score", "source_kind"])


def _backfill_documents(Document: object) -> None:
    for document in Document.objects.all():
        text = document.content or document.text or document.title
        basis = f"{document.title}\n{text}"
        document.text = text
        document.content_hash = _sha(_normalize(basis))
        document.simhash = _sha(" ".join(sorted(set(_normalize(basis).split()))))[:16]
        document.ingested_at = document.created_at
        document.save(update_fields=["text", "content_hash", "simhash", "ingested_at"])


def _backfill_clusters(Cluster: object) -> None:
    for cluster in Cluster.objects.all():
        cluster.canonical_title = cluster.canonical_title or cluster.label
        cluster.topic_label = cluster.topic_label or cluster.label
        cluster.first_seen_at = cluster.window_start
        cluster.last_seen_at = cluster.window_end
        cluster.trend_score = cluster.score
        cluster.confidence_score = cluster.score
        cluster.save(update_fields=_cluster_update_fields())


def _backfill_alerts(
    AlertHit: object,
    AlertHitDocument: object,
    Cluster: object,
) -> None:
    for alert in AlertHit.objects.all():
        cluster = _compat_cluster(alert, Cluster)
        alert.cluster = cluster
        alert.representative_document_id = alert.document_id
        alert.dedupe_key = alert.dedupe_key or alert.dedupe_hash
        alert.explanation = alert.explanation or f"Legacy alert migrated: {alert.title}"
        alert.detected_at = alert.occurred_at
        alert.save(update_fields=_alert_update_fields())
        _create_legacy_evidence(alert, AlertHitDocument)


def _compat_cluster(alert: object, Cluster: object) -> object:
    title = alert.title or "Legacy alert cluster"
    cluster, _created = Cluster.objects.get_or_create(
        label=f"legacy-alert-{alert.id}",
        window_start=alert.occurred_at,
        defaults=_compat_cluster_defaults(alert, title),
    )
    return cluster


def _create_legacy_evidence(alert: object, AlertHitDocument: object) -> None:
    if not alert.document_id:
        return
    AlertHitDocument.objects.get_or_create(
        alert_hit=alert,
        document_id=alert.document_id,
        defaults={"matched_text": alert.matched_text, "role": "representative"},
    )


def _compat_cluster_defaults(alert: object, title: str) -> dict[str, object]:
    return {
        "window_end": alert.occurred_at,
        "canonical_title": title,
        "summary": alert.matched_text,
        "topic_label": title[:240],
        "document_count": 1 if alert.document_id else 0,
        "source_count": 1 if alert.source_id else 0,
    }


def _cluster_update_fields() -> list[str]:
    return [
        "canonical_title",
        "topic_label",
        "first_seen_at",
        "last_seen_at",
        "trend_score",
        "confidence_score",
    ]


def _alert_update_fields() -> list[str]:
    return [
        "cluster",
        "representative_document",
        "dedupe_key",
        "explanation",
        "detected_at",
    ]


def _normalize(value: str) -> str:
    return " ".join(value.lower().split())


def _sha(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0005_alertdetector_alertfeedback_alerthitdocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerthit",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="monitoring.alertrule",
            ),
        ),
        migrations.AlterField(
            model_name="alerthit",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                    ("ignored", "Ignored"),
                    ("duplicate", "Duplicate"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="normalizeddocument",
            index=models.Index(
                fields=["content_hash"], name="monitoring__content_77a136_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizeddocument",
            index=models.Index(
                fields=["simhash"], name="monitoring__simhash_119ca3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizeddocument",
            index=models.Index(
                fields=["published_at"], name="monitoring__publish_fec467_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizeddocument",
            index=models.Index(
                fields=["ingested_at"], name="monitoring__ingeste_5b42e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertdetector",
            index=models.Index(
                fields=["detector_type", "enabled"],
                name="monitoring__detecto_8141a1_idx",
            ),
        ),
        migrations.AddField(
            model_name="alerthit",
            name="detector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="monitoring.alertdetector",
            ),
        ),
        migrations.AddField(
            model_name="alertfeedback",
            name="alert_hit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.alerthit",
            ),
        ),
        migrations.AddField(
            model_name="alertfeedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alerthitdocument",
            name="alert_hit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.alerthit",
            ),
        ),
        migrations.AddField(
            model_name="alerthitdocument",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.normalizeddocument",
            ),
        ),
        migrations.AddField(
            model_name="dedupegroup",
            name="representative_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="monitoring.normalizeddocument",
            ),
        ),
        migrations.RunPython(backfill_alert_engine_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="alerthit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rule__isnull", False),
                    ("detector__isnull", False),
                    _connector="OR",
                ),
                name="alert_hit_rule_or_detector",
            ),
        ),
        migrations.AddIndex(
            model_name="alertfeedback",
            index=models.Index(
                fields=["label", "created_at"], name="monitoring__label_21a1fc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alerthitdocument",
            constraint=models.UniqueConstraint(
                fields=("alert_hit", "document"), name="unique_alert_hit_document"
            ),
        ),
        migrations.AddIndex(
            model_name="dedupegroup",
            index=models.Index(
                fields=["group_type", "content_hash"],
                name="monitoring__group_t_48bedf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dedupegroup",
            index=models.Index(
                fields=["group_type", "simhash"], name="monitoring__group_t_ff70e8_idx"
            ),
        ),
    ]
