# Generated by Django 5.2.14 on 2026-05-11 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_backfill_alert_engine_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("dry_run", "Dry run"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_seen", models.PositiveIntegerField(default=0)),
                ("items_created", models.PositiveIntegerField(default=0)),
                ("items_updated", models.PositiveIntegerField(default=0)),
                ("items_skipped", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("cursor_before", models.CharField(blank=True, max_length=1200)),
                ("cursor_after", models.CharField(blank=True, max_length=1200)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(max_length=32)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("asset_class", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("country", models.CharField(blank=True, max_length=64)),
                ("sector", models.CharField(blank=True, max_length=128)),
                ("industry", models.CharField(blank=True, max_length=128)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "exchange"), name="uniq_symbol_exchange"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=512)),
                ("canonical_url", models.URLField(max_length=1200)),
                ("raw_url", models.URLField(blank=True, max_length=1200)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=300)),
                ("publisher", models.CharField(blank=True, max_length=300)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("tags_json", models.JSONField(blank=True, default=list)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("content_type", models.CharField(blank=True, max_length=64)),
                ("raw_payload_json", models.JSONField(blank=True, default=dict)),
                ("extraction_method", models.CharField(default="rss", max_length=20)),
                ("quality_score", models.FloatField(default=0)),
                ("dedupe_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.source",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "published_at"],
                        name="monitoring__source__e0127a_idx",
                    ),
                    models.Index(
                        fields=["canonical_url"], name="monitoring__canonic_688270_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("source", "external_id"),
                        name="uniq_source_external_id_if_exists",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("timeframe", models.CharField(max_length=10)),
                ("open", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                ("low", models.FloatField(blank=True, null=True)),
                ("close", models.FloatField(blank=True, null=True)),
                ("adjusted_close", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("dollar_volume", models.FloatField(blank=True, null=True)),
                ("trade_count", models.BigIntegerField(blank=True, null=True)),
                ("raw_payload_json", models.JSONField(blank=True, default=dict)),
                ("quality_flags_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.source",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.marketinstrument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["instrument", "timestamp"],
                        name="monitoring__instrum_136776_idx",
                    ),
                    models.Index(
                        fields=["source", "timestamp"],
                        name="monitoring__source__b6c506_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "source", "timeframe", "timestamp"),
                        name="uniq_market_bar",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("price", models.FloatField(blank=True, null=True)),
                ("bid", models.FloatField(blank=True, null=True)),
                ("ask", models.FloatField(blank=True, null=True)),
                ("last", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("dollar_volume", models.FloatField(blank=True, null=True)),
                ("trade_id", models.CharField(blank=True, max_length=128)),
                ("raw_payload_json", models.JSONField(blank=True, default=dict)),
                ("quality_flags_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.marketinstrument",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.source",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["instrument", "timestamp"],
                        name="monitoring__instrum_105e7e_idx",
                    ),
                    models.Index(
                        fields=["source", "timestamp"],
                        name="monitoring__source__fa7356_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("trade_id", ""), _negated=True),
                        fields=("instrument", "source", "timestamp", "trade_id"),
                        name="uniq_market_tick_trade",
                    )
                ],
            },
        ),
    ]
