# Generated by Django 5.2.14 on 2026-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_resource_locks_worker_heartbeats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeprofileconfig',
            name='profile_type',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='ComputeProfileTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('backend_preference', models.CharField(default='auto', max_length=32)),
                ('allow_cpu', models.BooleanField(default=True)),
                ('allow_gpu', models.BooleanField(default=False)),
                ('allow_cloud', models.BooleanField(default=False)),
                ('allow_ctypes', models.BooleanField(default=True)),
                ('max_vram_gb', models.FloatField(default=0)),
                ('max_ram_gb', models.FloatField(blank=True, null=True)),
                ('default_batch_size', models.PositiveIntegerField(default=64)),
                ('max_batch_size', models.PositiveIntegerField(default=256)),
                ('default_window', models.PositiveIntegerField(default=128)),
                ('max_window', models.PositiveIntegerField(default=512)),
                ('default_precision', models.CharField(default='float32', max_length=16)),
                ('allowed_tasks_json', models.JSONField(blank=True, default=list)),
                ('denied_tasks_json', models.JSONField(blank=True, default=list)),
                ('queue_enabled', models.BooleanField(default=True)),
                ('max_runtime_hours', models.FloatField(default=2.0)),
                ('budget_guard_enabled', models.BooleanField(default=False)),
                ('notes_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['enabled', 'slug'], name='dash_ptype_enabled_idx'), models.Index(fields=['allow_cloud', 'enabled'], name='dash_ptype_cloud_idx')],
            },
        ),
    ]
