# Generated by Django 5.2.14 on 2026-05-23 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_comparison_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicClusterSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_start', models.DateTimeField()),
                ('slice_end', models.DateTimeField()),
                ('slice_hours', models.PositiveIntegerField(default=24)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('novelty_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trend_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('severity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='monitoring.topiccluster')),
            ],
            options={
                'ordering': ['-slice_start'],
            },
        ),
        migrations.CreateModel(
            name='TopicClusterSliceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('similarity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('role', models.CharField(choices=[('representative', 'Representative'), ('evidence', 'Evidence'), ('duplicate', 'Duplicate'), ('contradiction', 'Contradiction'), ('source_of_claim', 'Source of claim')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.normalizeddocument')),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='monitoring.topicclusterslice')),
            ],
            options={
                'ordering': ['slice_id', '-overlap_score'],
            },
        ),
        migrations.AddIndex(
            model_name='topicclusterslice',
            index=models.Index(fields=['cluster', 'slice_start'], name='monitoring__cluster_6a115b_idx'),
        ),
        migrations.AddIndex(
            model_name='topicclusterslice',
            index=models.Index(fields=['slice_start', 'slice_hours'], name='monitoring__slice_s_42d24d_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicclusterslice',
            constraint=models.UniqueConstraint(fields=('cluster', 'slice_start', 'slice_hours'), name='unique_topic_cluster_slice'),
        ),
        migrations.AddConstraint(
            model_name='topicclusterslicedocument',
            constraint=models.UniqueConstraint(fields=('slice', 'document'), name='unique_topic_slice_document'),
        ),
    ]
