# Generated by Django 5.2.15 on 2026-06-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_financial_intelligence'),
        ('monitoring', '0012_topicclusterslice_topicclusterslicedocument_and_more'),
    ]

    operations = [
    ]
