# Generated manually for Phase 1 canonical Sourceflow schema.

from __future__ import annotations

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=80)),
                ("name", models.CharField(blank=True, max_length=240)),
                ("asset_type", models.CharField(default="equity", max_length=80)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("sector", models.CharField(blank=True, max_length=128)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("external_ids_json", models.JSONField(blank=True, default=dict)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            options={
                "ordering": ["symbol", "asset_type"],
                "indexes": [models.Index(fields=["symbol", "asset_type"], name="sourceflow__symbol_3da511_idx")],
                "constraints": [models.UniqueConstraint(fields=("symbol", "asset_type"), name="uniq_sourceflow_asset_symbol_type")],
            },
        ),
        migrations.CreateModel(
            name="AssumptionPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(choices=[("OWA", "Open-world assumption"), ("CWA", "Closed-world assumption"), ("PartialCWA", "Partial closed-world assumption"), ("CarefulCWA", "Careful closed-world assumption"), ("GCWA", "Generalized closed-world assumption"), ("EGCWA", "Extended generalized closed-world assumption"), ("ExtendedCWA", "Extended closed-world assumption"), ("UniqueNameAssumption", "Unique-name assumption"), ("NoUniqueNameAssumption", "No unique-name assumption")], max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("scope", models.CharField(blank=True, max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                ("params_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [models.Index(fields=["code", "scope"], name="sourceflow__code_55f4fb_idx")],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_name", models.CharField(max_length=240)),
                ("entity_type", models.CharField(default="Unknown", max_length=80)),
                ("external_ids_json", models.JSONField(blank=True, default=dict)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("sector", models.CharField(blank=True, max_length=128)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                "ordering": ["canonical_name"],
                "indexes": [models.Index(fields=["entity_type", "canonical_name"], name="sourceflow__entity__24384e_idx")],
                "constraints": [models.UniqueConstraint(fields=("canonical_name", "entity_type"), name="uniq_sourceflow_entity_identity")],
            },
        ),
        migrations.CreateModel(
            name="ProviderOwner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                ("canonical_name", models.CharField(max_length=180, unique=True)),
                ("homepage_url", models.URLField(blank=True, max_length=1200)),
                ("country", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["canonical_name"],
                "indexes": [models.Index(fields=["canonical_name"], name="sourceflow__canonic_309de7_idx")],
            },
        ),
        migrations.CreateModel(
            name="RetrievalTrace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                ("query_hash", models.CharField(db_index=True, max_length=128)),
                ("retriever_name", models.CharField(default="manual", max_length=120)),
                ("retrieval_mode", models.CharField(blank=True, max_length=80)),
                ("results_json", models.JSONField(blank=True, default=list)),
                ("citations_json", models.JSONField(blank=True, default=list)),
                ("assumptions_json", models.JSONField(blank=True, default=list)),
                ("retrieval_confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("extraction_confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("reasoning_confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [models.Index(fields=["retriever_name", "created_at"], name="sourceflow__retriev_ec925a_idx")],
            },
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                ("risk_type", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            options={
                "ordering": ["risk_type", "name"],
                "indexes": [models.Index(fields=["risk_type"], name="sourceflow__risk_ty_d2f55e_idx")],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                ("url", models.URLField(blank=True, max_length=1200)),
                ("source_type", models.CharField(choices=[("rss", "RSS"), ("html", "HTML"), ("api", "API"), ("filing", "Filing"), ("report", "Report"), ("manual", "Manual"), ("market_data", "Market data"), ("other", "Other")], default="other", max_length=40)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("language", models.CharField(default="en", max_length=16)),
                ("reliability_score", models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("bias_tags", models.JSONField(blank=True, default=list)),
                ("provider_owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sources", to="sourceflow.providerowner")),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["source_type"], name="sourceflow__source__d63b53_idx"), models.Index(fields=["country", "language"], name="sourceflow__country_5e01a8_idx")],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(blank=True, max_length=1200)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw_text", models.TextField(blank=True)),
                ("clean_text", models.TextField(blank=True)),
                ("content_hash", models.CharField(db_index=True, max_length=128)),
                ("language", models.CharField(default="en", max_length=16)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="sourceflow.source")),
            ],
            options={
                "ordering": ["-published_at", "-ingested_at", "id"],
                "indexes": [models.Index(fields=["source", "published_at"], name="sourceflow__source__f4553b_idx"), models.Index(fields=["content_hash"], name="sourceflow__content_a7ef9c_idx"), models.Index(fields=["language"], name="sourceflow__languag_300d46_idx")],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("char_start", models.PositiveIntegerField(default=0)),
                ("char_end", models.PositiveIntegerField(default=0)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("ingestion_version", models.CharField(blank=True, max_length=80)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="sourceflow.document")),
            ],
            options={
                "ordering": ["document_id", "chunk_index"],
                "indexes": [models.Index(fields=["document", "chunk_index"], name="sourceflow__documen_ef76ea_idx")],
                "constraints": [models.UniqueConstraint(fields=("document", "chunk_index"), name="uniq_sourceflow_document_chunk")],
            },
        ),
        migrations.CreateModel(
            name="EvidenceSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("char_start", models.PositiveIntegerField(default=0)),
                ("char_end", models.PositiveIntegerField(default=0)),
                ("extractor_name", models.CharField(default="manual", max_length=120)),
                ("extractor_version", models.CharField(blank=True, max_length=80)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("chunk", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="evidence_spans", to="sourceflow.documentchunk")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_spans", to="sourceflow.document")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence_spans", to="sourceflow.source")),
            ],
            options={
                "ordering": ["document_id", "char_start", "id"],
                "indexes": [models.Index(fields=["document", "char_start"], name="sourceflow__documen_a2e307_idx"), models.Index(fields=["source", "created_at"], name="sourceflow__source__6775f8_idx")],
            },
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=240)),
                ("alias_normalized", models.CharField(max_length=240)),
                ("alias_type", models.CharField(default="name", max_length=40)),
                ("namespace", models.CharField(blank=True, max_length=80)),
                ("entity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="sourceflow.entity")),
            ],
            options={
                "ordering": ["alias_normalized"],
                "indexes": [models.Index(fields=["alias_normalized", "namespace"], name="sourceflow__alias_n_542d8a_idx")],
                "constraints": [models.UniqueConstraint(fields=("alias_normalized", "namespace"), name="uniq_sourceflow_entity_alias_namespace")],
            },
        ),
        migrations.CreateModel(
            name="EntityMention",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mention_text", models.CharField(max_length=240)),
                ("entity_type", models.CharField(default="Unknown", max_length=80)),
                ("char_start", models.PositiveIntegerField(default=0)),
                ("char_end", models.PositiveIntegerField(default=0)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("extractor_name", models.CharField(default="manual", max_length=120)),
                ("extractor_version", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(default="candidate", max_length=40)),
                ("chunk", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entity_mentions", to="sourceflow.documentchunk")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entity_mentions", to="sourceflow.document")),
                ("entity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mentions", to="sourceflow.entity")),
                ("evidence_span", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entity_mentions", to="sourceflow.evidencespan")),
            ],
            options={
                "ordering": ["document_id", "char_start", "id"],
                "indexes": [models.Index(fields=["document", "char_start"], name="sourceflow__documen_e57de2_idx"), models.Index(fields=["entity", "document"], name="sourceflow__entity__9dafce_idx")],
            },
        ),
        migrations.CreateModel(
            name="InferenceRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule_id", models.CharField(max_length=160, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("rule_type", models.CharField(choices=[("deductive", "Deductive"), ("default", "Default"), ("abductive", "Abductive"), ("diagnostic", "Diagnostic"), ("risk_propagation", "Risk propagation"), ("source_comparison", "Source comparison"), ("retrieval_expansion", "Retrieval expansion")], default="deductive", max_length=40)),
                ("definition_json", models.JSONField(blank=True, default=dict)),
                ("confidence_delta", models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ("is_active", models.BooleanField(default=True)),
                ("assumption_policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rules", to="sourceflow.assumptionpolicy")),
            ],
            options={
                "ordering": ["rule_id"],
                "indexes": [models.Index(fields=["rule_type", "is_active"], name="sourceflow__rule_ty_6cb07f_idx")],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("predicate", models.CharField(max_length=160)),
                ("object_literal", models.TextField(blank=True)),
                ("polarity", models.CharField(choices=[("positive", "Positive"), ("negative", "Negative"), ("neutral", "Neutral"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("modality", models.CharField(choices=[("asserted", "Asserted"), ("alleged", "Alleged"), ("denied", "Denied"), ("forecasted", "Forecasted"), ("rumored", "Rumored"), ("confirmed", "Confirmed")], default="asserted", max_length=20)),
                ("tense", models.CharField(blank=True, max_length=40)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("incomplete", "Incomplete"), ("retracted", "Retracted"), ("disputed", "Disputed"), ("stale", "Stale")], default="active", max_length=40)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="sourceflow.document")),
                ("evidence_span", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="sourceflow.evidencespan")),
                ("object_entity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="object_claims", to="sourceflow.entity")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="sourceflow.source")),
                ("subject_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subject_claims", to="sourceflow.entity")),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [models.Index(fields=["subject_entity", "predicate"], name="sourceflow__subject_e20d89_idx"), models.Index(fields=["source", "created_at"], name="sourceflow__source__78a266_idx"), models.Index(fields=["document", "status"], name="sourceflow__documen_f18c9d_idx")],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("predicate", models.CharField(max_length=160)),
                ("object_literal", models.TextField(blank=True)),
                ("event_type", models.CharField(choices=[("earnings", "Earnings"), ("guidance", "Guidance"), ("lawsuit", "Lawsuit"), ("regulatory_action", "Regulatory action"), ("merger_acquisition", "Merger or acquisition"), ("supply_chain_disruption", "Supply-chain disruption"), ("product_launch", "Product launch"), ("executive_change", "Executive change"), ("credit_event", "Credit event"), ("macro_event", "Macro event"), ("commodity_shock", "Commodity shock"), ("currency_shock", "Currency shock"), ("geopolitical_event", "Geopolitical event"), ("analyst_revision", "Analyst revision"), ("insider_transaction", "Insider transaction"), ("liquidity_event", "Liquidity event"), ("lob_anomaly", "LOB anomaly"), ("other", "Other")], default="other", max_length=60)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("extraction_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("polarity", models.CharField(choices=[("positive", "Positive"), ("negative", "Negative"), ("neutral", "Neutral"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("magnitude", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("actor_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="actor_events", to="sourceflow.entity")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="sourceflow.document")),
                ("evidence_span", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="sourceflow.evidencespan")),
                ("object_entity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="object_events", to="sourceflow.entity")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="sourceflow.source")),
            ],
            options={
                "ordering": ["-event_time", "-created_at", "id"],
                "indexes": [models.Index(fields=["actor_entity", "event_type"], name="sourceflow__actor_e_ccd04d_idx"), models.Index(fields=["source", "event_time"], name="sourceflow__source__646d64_idx"), models.Index(fields=["document", "event_type"], name="sourceflow__documen_13f089_idx")],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEdge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edge_type", models.CharField(max_length=80)),
                ("source_node_type", models.CharField(max_length=80)),
                ("source_node_id", models.CharField(max_length=160)),
                ("target_node_type", models.CharField(max_length=80)),
                ("target_node_id", models.CharField(max_length=160)),
                ("confidence", models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("evidence_span", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_edges", to="sourceflow.evidencespan")),
                ("source_document", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_edges", to="sourceflow.document")),
            ],
            options={
                "ordering": ["source_node_type", "source_node_id", "edge_type"],
                "indexes": [models.Index(fields=["source_node_type", "source_node_id"], name="sourceflow__source__bf616d_idx"), models.Index(fields=["target_node_type", "target_node_id"], name="sourceflow__target__ce0835_idx"), models.Index(fields=["edge_type"], name="sourceflow__edge_ty_5a8f5e_idx")],
            },
        ),
        migrations.CreateModel(
            name="Belief",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("belief_type", models.CharField(max_length=80)),
                ("predicate", models.CharField(max_length=160)),
                ("object_literal", models.TextField(blank=True)),
                ("truth_status", models.CharField(choices=[("true_supported", "True supported"), ("false_supported", "False supported"), ("contradicted", "Contradicted"), ("unknown", "Unknown"), ("partially_supported", "Partially supported"), ("source_disputed", "Source disputed"), ("time_expired", "Time expired"), ("requires_human_review", "Requires human review")], default="unknown", max_length=40)),
                ("confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("stale", "Stale"), ("retracted", "Retracted"), ("superseded", "Superseded")], default="active", max_length=40)),
                ("assumption_policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="beliefs", to="sourceflow.assumptionpolicy")),
                ("created_by_rule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_beliefs", to="sourceflow.inferencerule")),
                ("object_entity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="object_beliefs", to="sourceflow.entity")),
                ("subject_entity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subject_beliefs", to="sourceflow.entity")),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [models.Index(fields=["belief_type", "truth_status"], name="sourceflow__belief_56aeaa_idx"), models.Index(fields=["subject_entity", "predicate"], name="sourceflow__subject_64b906_idx"), models.Index(fields=["status"], name="sourceflow__status_f0d403_idx")],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=80)),
                ("instrument_type", models.CharField(default="equity", max_length=80)),
                ("exchange", models.CharField(blank=True, max_length=80)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("external_ids_json", models.JSONField(blank=True, default=dict)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="instruments", to="sourceflow.asset")),
            ],
            options={
                "ordering": ["symbol", "exchange", "instrument_type"],
                "indexes": [models.Index(fields=["symbol", "exchange"], name="sourceflow__symbol_37d768_idx")],
                "constraints": [models.UniqueConstraint(fields=("symbol", "exchange", "instrument_type"), name="uniq_sourceflow_instrument_identity")],
            },
        ),
        migrations.CreateModel(
            name="Justification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("support_type", models.CharField(choices=[("supports", "Supports"), ("contradicts", "Contradicts"), ("derived_by_rule", "Derived by rule"), ("assumption", "Assumption")], default="supports", max_length=40)),
                ("weight", models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ("belief", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="justifications", to="sourceflow.belief")),
                ("rule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="justifications", to="sourceflow.inferencerule")),
                ("supporting_belief", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supporting_justifications", to="sourceflow.belief")),
                ("supporting_claim", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="justifications", to="sourceflow.claim")),
                ("supporting_event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="justifications", to="sourceflow.event")),
            ],
            options={
                "ordering": ["belief_id", "support_type", "id"],
                "indexes": [models.Index(fields=["belief", "support_type"], name="sourceflow__belief__99cfbf_idx")],
            },
        ),
        migrations.CreateModel(
            name="PortfolioPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("portfolio_id", models.CharField(max_length=160)),
                ("quantity", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("market_value", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("as_of", models.DateTimeField(default=django.utils.timezone.now)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="portfolio_positions", to="sourceflow.asset")),
                ("assumption_policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="portfolio_positions", to="sourceflow.assumptionpolicy")),
                ("instrument", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="portfolio_positions", to="sourceflow.instrument")),
            ],
            options={
                "ordering": ["portfolio_id", "asset_id", "-as_of"],
                "indexes": [models.Index(fields=["portfolio_id", "as_of"], name="sourceflow__portfol_a6f7dd_idx"), models.Index(fields=["asset", "as_of"], name="sourceflow__asset_i_2d2e1a_idx")],
            },
        ),
        migrations.CreateModel(
            name="RetractionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("provenance_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_type", models.CharField(max_length=80)),
                ("target_id", models.CharField(max_length=160)),
                ("reason", models.TextField()),
                ("previous_status", models.CharField(blank=True, max_length=80)),
                ("new_status", models.CharField(blank=True, max_length=80)),
                ("retracted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("affected_belief", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retraction_logs", to="sourceflow.belief")),
                ("affected_claim", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retraction_logs", to="sourceflow.claim")),
                ("affected_event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retraction_logs", to="sourceflow.event")),
                ("document", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retraction_logs", to="sourceflow.document")),
                ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retraction_logs", to="sourceflow.source")),
            ],
            options={
                "ordering": ["-retracted_at", "id"],
                "indexes": [models.Index(fields=["target_type", "target_id"], name="sourceflow__target__e57dcb_idx")],
            },
        ),
    ]
