# Generated by Django 5.2.15 on 2026-06-12 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourceflow', '0002_rename_sourceflow__symbol_3da511_idx_sourceflow__symbol_0e303b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_name', models.CharField(default='sourceflow_document_pipeline', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('params_json', models.JSONField(blank=True, default=dict)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_jobs', to='sourceflow.document')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=80)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('error', models.TextField(blank=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('model_versions_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_runs', to='sourceflow.pipelinejob')),
            ],
            options={
                'ordering': ['job_id', 'sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinejob',
            index=models.Index(fields=['status', 'created_at'], name='sourceflow__status_a52484_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinejob',
            index=models.Index(fields=['pipeline_name', 'status'], name='sourceflow__pipelin_c42a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestagerun',
            index=models.Index(fields=['job', 'status'], name='sourceflow__job_id_12a053_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestagerun',
            constraint=models.UniqueConstraint(fields=('job', 'stage_name'), name='uniq_sourceflow_pipeline_stage'),
        ),
    ]
